### ISSUE TITLE
JS doesn't load after Turbolinks page reload 

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#180]
JS in the admin isn't being loaded after Turbolinks page reloads. EG Taggle. 

![screen shot 2018-09-13 at 10 21 28](https://user-images.githubusercontent.com/282788/45483069-be6a5200-b747-11e8-9f86-0a8b8dd8893e.png)

Seems to be stem from having the JS in the `body_end` template block which is something @zarino wanted but I can't remember why anymore. I don't think this is supported by Turbolinks and is the cause of the problem we're seeing.

I think to fix this we either:

1. move the JS into the page head
2. we ditch Turbolinks

Any thoughts @garethrees / @zarino ?

**Comment by garethrees** [comment]
I don't have a real opinion on either tbh. If pushed, I'd say that we should do whatever Turbolinks expects us to do.

**Comment by zarino** [comment]
> which is something @zarino wanted but I can't remember why anymore.

Ideally, we’d use the `async` attribute on `<script>` tags in the `<head>`, which is pretty much the current state of the art: https://developers.google.com/speed/docs/insights/BlockingJS

It introduces a little bit of complexity, though, as asynchronous scripts aren’t guaranteed to run in any specific order, so if you have multiple scripts, you need to write your code to account for that.

Putting the `<script>`s at the end of the `<body>` is a way to get _some_ of the performance benefit of `async` (because rendering of—most of!—the page isn’t blocked while the browser downloads and parses JavaScript) without having to worry about execution order.

At least, that’s why we did it ;-)

**Comment by gbp** [comment]
Found this image [1] useful to understand the differences. The added complexity here is that we have IE9 magic comments for Taggle support which means we can't reliably `async`/`defer` loading [2].

The 3rd option would be to limit us to one JS file which would allow us to have the JS in the page head and async and not worry about execution order. PR incoming...

[1] https://stackoverflow.com/questions/10808109/script-tag-async-defer/39711009#39711009
[2] https://github.com/h5bp/lazyweb-requests/issues/42
