### ISSUE TITLE
Links to disclosure log redirect to an index page

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#217]
URLs from the Infreemation disclosure log endpoints are of the form:
  https://foi.infreemation.co.uk/redirect/hackney?id=45233

This redirects to the index at:
  https://foi.infreemation.co.uk/hackney/
  
The index correctly links to the request when there is a seed parameter:
  https://foi.infreemation.co.uk/hackney/request?id=45233&seed=5PT8SdHg9EYVUhm15RMFJjp3ZHakNl72jdrpeztmtN1jgGQBeE

The seed parameter is different for each published request and the seed parameter isn't included in the JSON returned from Infreemation.

**Comment by garethrees** [comment]
Figured this out:

Here’s an example snippet of the JSON returned by the API for a request:

```
"generated": "2019-02-22 00:00",
"ref": "FOI-2458",
"type": "FOI",
"datecreated": "2019-01-21",
"dateclosed": "2019-01-28",
"datepublished": "2019-01-28",
"url": "https://foi.infreemation.co.uk/redirect/hackney?id=63434",
```

Following https://foi.infreemation.co.uk/redirect/hackney?id=63434 results in a number of redirects, ultimately taking you to the disclosure log home page.

Here’s the chain of redirects:

```
$ curl --silent --head "https://foi.infreemation.co.uk/redirect/hackney?id=63434" | grep Location
Location: http://foi.infreemation.co.uk/hackney/request?id=63434&seed=Ys79Qm5x6AMFeVOCvPZI

$ curl --silent --head "http://foi.infreemation.co.uk/hackney/request?id=63434&seed=Ys79Qm5x6AMFeVOCvPZI" | grep Location
Location: https://foi.infreemation.co.uk/hackney/request

$ curl --silent --head "https://foi.infreemation.co.uk/hackney/request" | grep Location
Location: /hackney/
```

It looks like the initial redirect is incorrectly configured to use the HTTP protocol – rather than HTTPS – resulting in the redirect back to the disclosure log home page.

Using HTTPS results in us getting taken to the correct individual request page:

```
$ curl --silent --head "http://foi.infreemation.co.uk/hackney/request?id=63434&seed=Ys79Qm5x6AMFeVOCvPZI" | head -n 1
HTTP/1.1 302 Object moved

$ curl --silent --head "https://foi.infreemation.co.uk/hackney/request?id=63434&seed=Ys79Qm5x6AMFeVOCvPZI" | head -n 1
HTTP/1.1 200 OK
```

Sent an email to Infreemation and Hackney here https://groups.google.com/a/mysociety.org/forum/#!topic/clientsupport-council-foi/medjFMlhrVI

**Comment by garethrees** [comment]
They've fixed this now
