### ISSUE TITLE
As a council employee, I want to know what resources were shown to a citizen making an FOI request, and whether that request was completed, in order to assess the usefulness of showing resources in the request process

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#23]

**Comment by garethrees** [comment]
We _think_ the data we can show here is:

Resource Title | URL | Shown Count | Request Abandoned Count | Request Made Count
--- | --- | --- | --- | --- 
Annual Report 2018 | https://2018.example.com | 100 | 20 | 80
Some existing FOI question | https://example.com/disclosure-log/FOI-1 | 10 | 9 | 1

So in the above examples:

* The first resource has been shown 100 times, but only prevented 20% of requests where this resource was shown.
* The second resource has been shown 10 times, but prevented 90% of requests where it was shown.

I was initially thinking we can display this on the `index` list of each type of resource:

![screen shot 2018-05-22 at 09 58 41](https://user-images.githubusercontent.com/282788/40352465-c8d18d76-5da6-11e8-987e-29f5346b3617.png)

But we should check whether they want this in-app, or whether a CSV export would be more useful.

**Comment by garethrees** [comment]
@zarino pinging for your thoughts here. @gbp need to figure out if we can get this data (we think we can, but need to actually work out the mechanics of it), but I think _something_ like this should be achievable.

**Comment by zarino** [comment]
This is a good start, and it’s roughly what we were all envisaging when we discussed analytics at the design workshops.

You didn’t mention it explicitly, but we will _also_ want to track _clicks_ on each resource. A resource should only be considered to have "prevented" a request if: 1) It was shown, 2) the user clicked on it, and 3) the user did not return to continue with their original request.

As it recall it, the primary thing Hackney want is to be able to spot resources that _they think are relevant_ to a person’s request, but that people _aren’t_ clicking on and are just continuing to make a request, probably for information they _could_ have found in the suggested resource. And they want this data because it’ll help them hone the keywords and descriptions attached to the resources, so that they can become more accurate over time.

My instinct is, to do this, we’ll need to focus _more_ on keywords and _less_ on resources, if that makes sense.

Showing how often a particular resource "prevented" a request is fairly useless without knowing _which keywords_ resulted in that request being shown. A resource might be spot-on for someone entering one of its keywords, but might be totally useless for someone entering one of its other keywords. We want to help staff discover that, so that they can tweak the keywords to be more relevant.

**Comment by garethrees** [comment]
Waiting on feedback

**Comment by garethrees** [comment]
On the last call we had with them, Sarah said do a CSV export for now. We can always add an in-app view if we have a little time at the end of the project; it might only take an hour or two.

**Comment by garethrees** [comment]
They're happy with the approach, so we can consider all blockers removed now.
